services:
  frontend_dev:
    build:
      context: ./frontend
    container_name: frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_dev:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_dev:/app/.venv

volumes:
  frontend_dev:
  backend_dev: